### ISSUE TITLE
Tag preparation for LCG_99

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#761]
LCG_99 will be a transition release, based on a fixed ROOT 6.22, the Python default will be 3, support will be extended to centos8 and ubuntu20. ROOT 6.22/06 has been tagged but not announced. They say that they should be able to start building by early next week.

We should have in mind to provide a stable tag that mostly addresses outstanding issues (units) and have the edm4hep extension ready for that, we need
 - [x] fix or resolution of #760 
 - [x] thorough review of #753 and any outstanding issues around units, like #759 
 - [x] EDH4hep extension #758 
 - [x] tag EDM4hep (~~needs  key4hep/EDM4hep#98 merged for mac builds~~)
 - [x] tag podio (~~needs  AIDASoft/podio#153 merged for mac builds~~)
 - [x] new tags of LCIO 
 - [x] new tag of SIO (integration into LCG [issue](https://sft.its.cern.ch/jira/projects/SPI/issues/SPI-1762))
 - [x] fix regression for Geant4 support #763 

anything else?

**Comment by vvolkl** [comment]
key4hep/EDM4hep#98  is merged, will make a tag now

for podio I think you meant https://github.com/AIDASoft/podio/pull/153? @gaede

**Comment by andresailer** [comment]
Next DD4hep version will be 1.15?

**Comment by petricm** [comment]
Yes, that was my idea.

**Comment by petricm** [comment]
All is merged for the next LCG release
https://gitlab.cern.ch/sft/lcgcmake/-/merge_requests/570
