### ISSUE TITLE
CI Re-baselining

### ISSUE THREAD

**Issue by andresailer** [AIDASoft/DD4hep#943]
We should probably drop some of the old CI builds and pick up the newer ones (LCG_101, 102)

* [x] Newer lcg builds, key4hep stacks #946 
* [x] add a build with DD4HEP_USE_GEANT4_UNITS enabled: #956 
* [x] clang-tidy header guard check #957
